### ISSUE TITLE
fix: download files with more than 5MB in size

### ISSUE THREAD

**Issue by ntorga** [goinfinite/os#48]
Bigger files need to be downloaded via stream rather than c.File.

**Comment by polillomm** [comment]
A new route `/files/download,` was created to avoid interfering with the `GET` request that essentially brings back the file content if possible (total size). The download is not an alternative way to read the file, as it is downloaded to the user's machine, so it made a lot of sense to separate it into a different route. This doesn’t impact the current scope of the **FileManager** at all.
